### ISSUE TITLE
I follow the README to setup the server, but I got the error：The table `public.chatgpt_account` does not exist in the current database.

### ISSUE THREAD

**Issue by BertieGo** [bytemate/chatapi#18]
npm run seed

> chatapi@0.0.1 seed
> prisma db seed

Environment variables loaded from .env
Running seed command `ts-node prisma/seed.ts` ...
PrismaClientKnownRequestError:
Invalid `prisma.chatGPTAccount.deleteMany()` invocation in
/Users/huangwei/lalaland/chatapi/prisma/seed.ts:8:31

   5 const chatgptEmail = process.env.CHATGPT_EMAIL;
   6 const chatgptPassword = process.env.CHATGPT_PASSWORD;
   7 async function main() {
→  8   await prisma.chatGPTAccount.deleteMany()
  The table `public.chatgpt_account` does not exist in the current database.
    at RequestHandler.handleRequestError (/Users/huangwei/lalaland/chatapi/node_modules/@prisma/client/runtime/index.js:28658:13)
    at RequestHandler.request (/Users/huangwei/lalaland/chatapi/node_modules/@prisma/client/runtime/index.js:28640:12)
    at async consumer (/Users/huangwei/lalaland/chatapi/node_modules/@prisma/client/runtime/index.js:29618:18)
    at async PrismaClient._request (/Users/huangwei/lalaland/chatapi/node_modules/@prisma/client/runtime/index.js:29639:16)
    at async main (/Users/huangwei/lalaland/chatapi/prisma/seed.ts:8:3) {
  code: 'P2021',
  clientVersion: '4.1.0',
  meta: { table: 'public.chatgpt_account' }
}

**Comment by BertieGo** [comment]
It seems like that tables of database have not been initialized

**Comment by BertieGo** [comment]
I have fixed it by running `` npm run  migrate:dev``.
