### ISSUE TITLE
Invalid `prisma.chatGPTAccount.deleteMany()` invocation in seed.ts

### ISSUE THREAD

**Issue by yixian3500** [bytemate/chatapi#2]
Hi thanks for develop this project, this is to seek your help on this issue
when I ran the "npm run seed" command , returned this ,

> chatapi@0.0.1 seed
> prisma db seed

Environment variables loaded from .env
Running seed command `ts-node prisma/seed.ts` ...
PrismaClientKnownRequestError: 
Invalid `prisma.chatGPTAccount.deleteMany()` invocation in
/Users/yx/projects/chatapi/prisma/seed.ts:8:31

   5 const chatgptEmail = process.env.CHATGPT_EMAIL;
   6 const chatgptPassword = process.env.CHATGPT_PASSWORD;
   7 async function main() {
→  8   await prisma.chatGPTAccount.deleteMany()
  The table `blog.chatgpt_account` does not exist in the current database.
    at RequestHandler.handleRequestError (/Users/yx/projects/chatapi/node_modules/@prisma/client/runtime/index.js:28658:13)
    at RequestHandler.request (/Users/yx/projects/chatapi/node_modules/@prisma/client/runtime/index.js:28640:12)
    at async consumer (/Users/yx/projects/chatapi/node_modules/@prisma/client/runtime/index.js:29618:18)
    at async PrismaClient._request (/Users/yx/projects/chatapi/node_modules/@prisma/client/runtime/index.js:29639:16)
    at async main (/Users/yx/projects/chatapi/prisma/seed.ts:8:3) {
  code: 'P2021',
  clientVersion: '4.1.0',
  meta: { table: 'blog.chatgpt_account' }
}

🌱  The seed command has been executed.

**Comment by aetherwu** [comment]
Duplicated issue:
https://github.com/bytemate/chatapi/issues/3

**Comment by yixian3500** [comment]
I updated the table from pgAdmin to sloved this issue.

**Comment by aetherwu** [comment]
> I updated the table from pgAdmin to sloved this issue.

However this did not sovle this issue.
