### ISSUE TITLE
The table `blog.chatgpt_account` does not exist in the current database.

### ISSUE THREAD

**Issue by aetherwu** [bytemate/chatapi#3]
Had processed step 3 with .env & account.json & token(with filled balance).

Then run into:
#**npm run seed**

```
> chatapi@0.0.1 seed
> prisma db seed

Environment variables loaded from .env
Running seed command `ts-node prisma/seed.ts` ...
PrismaClientKnownRequestError:
Invalid `prisma.chatGPTAccount.deleteMany()` invocation in
/chatapi/prisma/seed.ts:8:31

   5 const chatgptEmail = process.env.CHATGPT_EMAIL;
   6 const chatgptPassword = process.env.CHATGPT_PASSWORD;
   7 async function main() {
→  8   await prisma.chatGPTAccount.deleteMany()
  **The table `blog.chatgpt_account` does not exist in the current database.**
    at RequestHandler.handleRequestError (/chatapi/node_modules/@prisma/client/runtime/index.js:28658:13)
    at RequestHandler.request (/chatapi/node_modules/@prisma/client/runtime/index.js:28640:12)
    at async consumer (/chatapi/node_modules/@prisma/client/runtime/index.js:29618:18)
    at async PrismaClient._request (/chatapi/node_modules/@prisma/client/runtime/index.js:29639:16)
    at async main (/chatapi/prisma/seed.ts:8:3) {
  code: 'P2021',
  clientVersion: '4.1.0',
  meta: { table: 'blog.chatgpt_account' }
}

🌱  The seed command has been executed.
```

**Comment by aetherwu** [comment]
In folder prisma, execute command:

    ```sh
    npx prisma db push
    ```

Should work.
